---
title: "EDA - 02"
subtitle: "Gráficas 1era Parte: Absolutos"
output: html_notebook
---

```{r}
library(dplyr)
library(tidyr)
library(ggplot2)
library(plotly)
```

```{r}
if(!exists("all_gather02")){
  all_gather02<-readRDS("data/tasas_diarias_x_region_02.rds")
}
all_gather02%>%
  mutate(
    mesdia=round(mesdia,2)
  )
```

# Nacionales

```{r,fig.width=10,fig.height=7,fig.align='left'}
vartmp<-"cifras"
gg00<-ggplot(all_gather02%>%
               select(-TOTALES,-starts_with("tasa_"),-starts_with("gap_"))%>%
               filter(Region%in%c("Nacional"))%>%
               # filter_(.dots = paste0(vartmp," > 0"))%>%#paste0(vartmp,"!=-99"))%>%
               mutate(
                 mesdia=as.factor(as.character.numeric_version(round(mesdia,2))),
                 Region=as.factor(Region)
               )%>%
               gather(metrica,cifras,-Region,-mesdia)%>%
               filter_(.dots = paste0(vartmp," >= 0")),#paste0(vartmp,"!=-99")), 
             aes(x=mesdia,colour=metrica,group=1))

ggplotly(
    gg00 +
      geom_line(aes_string(y=vartmp)) + 
      theme(axis.text.x = element_text(angle = 90, hjust = 1))+
      labs(title = "Métricas Nacionales por día")
)
```



```{r,fig.width=10,fig.height=7,fig.align='left'}
vartmp_x<-"ConfirmadosEstimados"
vartmp<-"cifras"
gg00<-ggplot(all_gather02%>%
               select(-TOTALES,-starts_with("tasa_"),-starts_with("gap_"))%>%
               filter(Region%in%c("Nacional"))%>%
               # filter_(.dots = paste0(vartmp," > 0"))%>%#paste0(vartmp,"!=-99"))%>%
               mutate(
                 mesdia=as.factor(as.character.numeric_version(round(mesdia,2))),
                 Region=as.factor(Region)
               )%>%
               gather(metrica,cifras,-one_of(c("Region","mesdia",vartmp_x)))%>%
               filter_(.dots = paste0(vartmp," >= 0")),#paste0(vartmp,"!=-99")), 
             aes(colour=metrica,group=1))

ggplotly(
    gg00 +
      geom_point(aes_string(x=vartmp_x,y=vartmp)) + 
      theme(axis.text.x = element_text(angle = 90, hjust = 1))+
      labs(title = "Confirmados (estimados) vs las otras Métricas Nacionales")
)
```

# Por Región {.tabset}

## Confirmados vs Hospitalizados, Recuperados, Cuidados Intensivos, Fallecidos
```{r,fig.width=10,fig.height=10,fig.align='left'}
vartmp_x<-"ConfirmadosEstimados"
vartmp<-"cifras"
gg00<-ggplot(all_gather02%>%
               select(-TOTALES,-starts_with("tasa_"),-starts_with("gap_"))%>%
               filter(!Region%in%c("Nacional"))%>%
               # filter_(.dots = paste0(vartmp," > 0"))%>%#paste0(vartmp,"!=-99"))%>%
               mutate(
                 mesdia=as.factor(as.character.numeric_version(round(mesdia,2))),
                 Region=as.factor(Region)
               )%>%
               gather(metrica,cifras,-one_of(c("Region","mesdia",vartmp_x)))%>%
               filter_(.dots = paste0(vartmp," >= 0")),#paste0(vartmp,"!=-99")), 
             aes(colour=metrica,group=1)) +
  facet_wrap(~Region,scales = "free",nrow = 4) +
  theme(strip.background = element_blank(), strip.placement = "outside")
# print(
ggplotly(
    gg00 +
      geom_point(aes_string(x=vartmp_x,y=vartmp)) + 
      theme_void() + theme(legend.position="none")+
      labs(title = "Confirmados (estimados) vs las otras Métricas por Región")
      # theme(axis.text.x = element_text(angle = 90, hjust = 1))
)
# )
```

## Confirmados por dìa & por Región 
```{r,fig.width=10,fig.height=7,fig.align='left'}
vartmp<-"ConfirmadosEstimados"
gg00<-ggplot(all_gather02%>%
               filter(!Region%in%c("Nacional"))%>%
               filter_(.dots = paste0(vartmp," > 0"))%>%#paste0(vartmp,"!=-99"))%>%
               mutate(
                 mesdia=as.factor(as.character.numeric_version(round(mesdia,2))),
                 Region=as.factor(Region)
               ), aes(x=mesdia,colour=Region,group=1))

ggplotly(
    gg00 +
      geom_line(aes_string(y=vartmp)) + 
      theme(axis.text.x = element_text(angle = 90, hjust = 1))+
      labs(title = paste0(vartmp," por día & por Región"))
)
```


## Hospitalizados por dìa & por Región 
```{r,fig.width=10,fig.height=7,fig.align='left'}
vartmp<-"Hospitalizados"
gg00<-ggplot(all_gather02%>%
               filter(!Region%in%c("Nacional"))%>%
               filter_(.dots = paste0(vartmp," > 0"))%>%#paste0(vartmp,"!=-99"))%>%
               mutate(
                 mesdia=as.factor(as.character.numeric_version(round(mesdia,2))),
                 Region=as.factor(Region)
               ), aes(x=mesdia,colour=Region,group=1))

ggplotly(
    gg00 +
      geom_line(aes_string(y=vartmp)) + 
      theme(axis.text.x = element_text(angle = 90, hjust = 1))+
      labs(title = paste0(vartmp," por día & por Región"))
)
```



## Recuperados por dìa & por Región
```{r,fig.width=10,fig.height=7,fig.align='left'}
vartmp<-"Recuperados"
gg00<-ggplot(all_gather02%>%
               filter(!Region%in%c("Nacional"))%>%
               filter_(.dots = paste0(vartmp," > 0"))%>%#paste0(vartmp,"!=-99"))%>%
               mutate(
                 mesdia=as.factor(as.character.numeric_version(round(mesdia,2))),
                 Region=as.factor(Region)
               ), aes(x=mesdia,colour=Region,group=1))

ggplotly(
    gg00 +
      geom_line(aes_string(y=vartmp)) + 
      theme(axis.text.x = element_text(angle = 90, hjust = 1))+
      labs(title = paste0(vartmp," por día & por Región"))
)
```


## Cuidados Intensivos por dìa & por Región
```{r,fig.width=10,fig.height=7,fig.align='left'}
vartmp<-"CuidadosIntensivos"
gg00<-ggplot(all_gather02%>%
               filter(!Region%in%c("Nacional"))%>%
               filter_(.dots = paste0(vartmp," > 0"))%>%#paste0(vartmp,"!=-99"))%>%
               mutate(
                 mesdia=as.factor(as.character.numeric_version(round(mesdia,2))),
                 Region=as.factor(Region)
               ), aes(x=mesdia,colour=Region,group=1))

ggplotly(
    gg00 +
      geom_line(aes_string(y=vartmp)) + 
      theme(axis.text.x = element_text(angle = 90, hjust = 1))+
      labs(title = paste0(vartmp," por día & por Región"))
)
```

## Fallecidos por dìa & por Región
```{r,fig.width=10,fig.height=7,fig.align='left'}
vartmp<-"Fallecidos"
gg00<-ggplot(all_gather02%>%
               filter(!Region%in%c("Nacional"))%>%
               filter_(.dots = paste0(vartmp," > 0"))%>%#paste0(vartmp,"!=-99"))%>%
               mutate(
                 mesdia=as.factor(as.character.numeric_version(round(mesdia,2))),
                 Region=as.factor(Region)
               ), aes(x=mesdia,colour=Region,group=1))

ggplotly(
    gg00 +
      geom_line(aes_string(y=vartmp)) + 
      theme(axis.text.x = element_text(angle = 90, hjust = 1))+
      labs(title = paste0(vartmp," por día & por Región"))
)
```
